# Generated by Django 5.2.1 on 2025-05-31 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'établissement")),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('quartier', models.CharField(max_length=100, verbose_name='Quartier')),
                ('logo', models.ImageField(blank=True, default='defaults/school_logo.png', upload_to='school_logos/', verbose_name="Logo de l'établissement")),
                ('document_header', models.ImageField(blank=True, null=True, upload_to='school_headers/', verbose_name='En-tête des documents')),
                ('foundation_date', models.DateField(blank=True, null=True, verbose_name='Date de fondation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Établissement scolaire',
                'verbose_name_plural': 'Établissements scolaires',
                'unique_together': {('name', 'ville', 'quartier')},
            },
        ),
    ]
