# Generated by Django 5.2.1 on 2025-05-31 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_gradeoption_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYearLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels_in_grade', to='core.grade', verbose_name='Série')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances_in_level', to='core.level', verbose_name='Niveau')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels_in_year', to='core.schoolyear', verbose_name='Année scolaire')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': "Niveau d'année scolaire",
                'verbose_name_plural': "Niveaux d'année scolaire",
                'ordering': ['school_year', 'grade', 'level'],
                'unique_together': {('school_year', 'grade', 'level')},
            },
        ),
    ]
