# Generated by Django 5.2.1 on 2025-05-31 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_schoolyearlevel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolyearlevel',
            options={'verbose_name': 'Niveau scolaire annuel', 'verbose_name_plural': 'Niveaux scolaires annuels'},
        ),
        migrations.AlterUniqueTogether(
            name='schoolyearlevel',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='schoolyearlevel',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoolyear_levels', to='core.grade', verbose_name='Cycle (Grade)'),
        ),
        migrations.AlterField(
            model_name='schoolyearlevel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active ou désactive ce niveau pour cette année scolaire.', verbose_name='Actif ?'),
        ),
        migrations.AlterField(
            model_name='schoolyearlevel',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoolyear_levels', to='core.level', verbose_name='Niveau (Classe)'),
        ),
        migrations.AlterField(
            model_name='schoolyearlevel',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoolyear_levels', to='core.schoolyear', verbose_name='Année scolaire'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolyearlevel',
            unique_together={('school_year', 'level')},
        ),
    ]
