# Generated by Django 5.2.1 on 2025-05-31 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_schoolyearlevel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('name', models.CharField(help_text='Exemple: A, B, C, Rouge, Bleue, etc.', max_length=50, verbose_name='Nom de la classe')),
                ('capacity', models.PositiveIntegerField(default=40, help_text='Nombre maximal d’élèves que peut contenir cette classe.', verbose_name='Capacité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('school_year_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='core.schoolyearlevel', verbose_name='Niveau scolaire annuel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'Classe',
                'verbose_name_plural': 'Classes',
                'unique_together': {('school_year_level', 'name')},
            },
        ),
    ]
