# Generated by Django 5.2.1 on 2025-05-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='has_option',
            field=models.BooleanField(default=True, help_text="Si cest possible d'avoir des options", verbose_name='A des options'),
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
