# Generated by Django 5.2.1 on 2025-05-31 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_grade_has_option_delete_classroom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('name', models.CharField(help_text='Ex: Terminale A, 6ème B', max_length=50, verbose_name='nom de la classe')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('grade_option', models.ForeignKey(blank=True, help_text='Option du grade, ex: Sciences, Lettres...', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classrooms', to='core.gradeoption', verbose_name='option')),
                ('school_year_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='core.schoolyearlevel', verbose_name='niveau annuel')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modifié par')),
            ],
            options={
                'verbose_name': 'classe',
                'verbose_name_plural': 'classes',
                'unique_together': {('school_year_level', 'name', 'grade_option')},
            },
        ),
    ]
