# Generated by Django 5.2.1 on 2025-05-31 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_classroom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='has_option',
            field=models.BooleanField(default=False, help_text="Si cest possible d'avoir des options", verbose_name='A des options'),
        ),
    ]
